# Generated by Django 3.1.7 on 2021-04-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='stockResults',
            field=models.ManyToManyField(to='app.StockList'),
        ),
    ]
