# Generated by Django 3.1.7 on 2021-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210407_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='stockResults',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stockResults',
            field=models.ManyToManyField(to='app.StockList'),
        ),
    ]
