# Generated by Django 3.1.7 on 2021-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210406_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='negativeSentimentCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='postiveSentimentCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
