# Generated by Django 3.1.7 on 2021-04-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210409_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='stock_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
